name: Docker Hub readme
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/dockerhub-readme.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/tinier
          short-description: SHORT_DESCRIPTION
          readme-filepath: README.md
